### ISSUE TITLE
Line number annotation on quest preview side of editor

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#259] opened 2017-04-25 03:36 UTC
*Migrated to expeditionrpg/expedition#297 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

Since we track the line number of the currently previewed quest card, we can display the line number somewhere in the preview window and have it be clickable to snap the editor view to the currently-displayed quest node.

**Comment by toddmedema** [comment] 2017-04-25 13:05
Duplicate of https://github.com/ExpeditionRPG/expedition-quest-creator/issues/254, though I like this implementation better

**Closed** 2018-07-01 16:16 UTC
Labels: backlog
