### ISSUE TITLE
Mobile friendly editor home page

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#146] opened 2017-01-15 14:52 UTC
Mobile version of the homepage is weirdly left-aligned. We should scale the video widget appropriately and possibly disable the sign-in, indicating that a particular browser resolution is required.

**Comment by smartin015** [comment] 2017-04-22 11:54
Fixed with #253

**Comment by toddmedema** [comment] 2017-04-22 18:39
Doesn't seem fixed?

<img width="338" alt="screen shot 2017-04-22 at 2 38 26 pm" src="https://cloud.githubusercontent.com/assets/775657/25307110/694aaae6-2769-11e7-9008-bf079f4e8ee1.png">

**Comment by toddmedema** [comment] 2017-05-06 16:29
Closing, duplicate of https://github.com/ExpeditionRPG/expedition-quest-creator/issues/204

**Closed by toddmedema** 2017-05-06 16:29 UTC
Labels: bug
