### ISSUE TITLE
Grammar checking

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#487] opened 2018-05-16 23:33 UTC
*Migrated to expeditionrpg/expedition#338 by [spacetelescope/github-issues-import](https://github.com/spacetelescope/github-issues-import)*

We have spell checking... we should also have grammar checking!

**Comment by toddmedema** [comment] 2018-05-17 02:13
Note that we would really want grammar /suggestions/ not just underlines. And to have suggestions, we'd first need interactions: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/488

This is actually a duplicate of a backlog issue: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/342

One option would be https://www.languagetool.org/, which includes spellchecking and (at least of research a year ago) had an offline option we could host ourselves 

Note that any spellcheck solution would need to support custom vocabulary since there are a lot of traditionally uncommon RPG words like undead that spellcheckers might not allow by default.

**Closed** 2018-07-01 19:05 UTC
Labels: high effort, high impact
