### ISSUE TITLE
Context editor uneditable past first "play from cursor"

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#461] opened 2018-01-23 13:06 UTC
Had an issue where the context editor initial vars section was edited, "play from cursor" was clicked, and the context editor was focused and edited again. The text kept resetting back to the play-from-cursor value.

**Comment by toddmedema** [comment] 2018-03-31 03:51
Closing, duplicate of https://github.com/ExpeditionRPG/expedition-quest-creator/issues/468

**Closed by toddmedema** 2018-03-31 03:51 UTC
Labels: high impact
