### ISSUE TITLE
Prevent spellchecks inside ops inside gotos

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-quest-creator#406] opened 2017-10-08 19:38 UTC
`**{{_.viewCount("mysteryrelease") ==0}} goto mysteryrelease**` shows spelling mistake "_.viewCount"

**Comment by toddmedema** [comment] 2017-11-26 16:55
Closing, unable to reproduce. Must have been fixed as part of another update.

**Closed by toddmedema** 2017-11-26 16:55 UTC
