### ISSUE TITLE
Making the QDL coding interface more pleasing (Low) (Enhancement)

### ISSUE THREAD

**Issue by danielwiktorczyk** [ExpeditionRPG/expedition-quest-creator#203] opened 2017-03-05 23:56 UTC
Specifically, having an option to write in the QDL with 

- Times New Roman font, with the option of having it enabled exclusively for Text code (minus context and other attributes inline with the text code lines)
- A black textured background (as the combat's in app pages have)
- A parchment background with black colored code (like the regular in app pages have)
- etc

I'm always discouraged when I have a burst of creativity for a quest, but have to write in a dull coding environment. I don't know if tweaking the code script to accommodate font and background changes is possible / a popular thought though ; )

**Comment by toddmedema** [comment] 2017-03-06 03:03
@danielwiktorczyk great idea! First time we've heard it, so doesn't seem to be super popular yet, but good to starting thinking about :)

Also, don't know if you saw, but we just released a survey for quest creators to prioritize the next big features and fixes - only takes 2 minutes, we'd love your input! https://docs.google.com/forms/d/1QohR-xYQmoDt1Ji4XQjzCQTnmP-MWrDEX-n1PFUmqrw

**Comment by smartin015** [comment] 2017-05-06 17:09
Now a duplicate of #206.

**Closed by smartin015** 2017-05-06 17:09 UTC
Labels: enhancement
